// ACTION TYPES
export const actionTypes = {
	LOG_IN_SUCCESS: 'LOG_IN_SUCCESS',
	LOG_IN_FAILURE: 'LOG_IN_FAILURE',
	LOGGED_OFF: 'LOGGED_OFF',
	SET_CATEGORIES: 'SET_CATEGORIES',

	ERROR_GETTING_USERS: 'ERROR_GETTING_USERS',
	SET_ACTIVE_USERS: 'SET_ACTIVE_USERS',
	CLEAR_ACTIVE_USERS: 'CLEAR_ACTIVE_USERS',

	START_ACTIVATE_USER: 'START_ACTIVATE_USER',
	ACTIVATE_USER_FAILURE: 'ACTIVATE_USER_FAILURE',
	ACTIVATE_USER_SUCCESS: 'ACTIVATE_USER_SUCCESS',

	PENDINGS_GETTING_FAILURE: 'PENDINGS_GETTING_FAILURE',
	SET_PENDINGS: 'SET_PENDINGS',
	CLEAR_PENDINGS: 'CLEAR_PENDINGS',

	CLEAR_USER: 'CLEAR_USER',
	SELECT_USER: 'SELECT_USER',
	USER_GETTING_FAILURE: 'USER_GETTING_FAILURE',
	
	EDIT_USER_SUCCESS: 'EDIT_USER_SUCCESS',
	EDIT_USER_FAILURE: 'EDIT_USER_FAILURE',
};