export const PAGE_SIZE = 20;

export const INFO_TYPES= {
    ACC_DETAILS: 'ACC_DETAILS',
    ACTIVITIES: 'ACTIVITIES', 
    MONEY: 'MONEY',
    CLIENTS: 'CLIENTS',
    LIST_OF_PROS: 'LIST_OF_PROS',
};